version: '3'
services:
  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq//

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"    # RabbitMQ communication port
      - "15672:15672"  # RabbitMQ management dashboard

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"   # Elasticsearch API port

  worker:
    build: ./app
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - elasticsearch
    restart: always
